# Generated by Django 3.1 on 2024-09-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MOU',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Partner', models.CharField(max_length=255)),
                ('Sector', models.CharField(max_length=255)),
                ('Purpose', models.CharField(max_length=255)),
                ('Department', models.CharField(max_length=255)),
                ('Duration', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'MOU',
            },
        ),
    ]
