# Generated by Django 3.1 on 2024-09-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_mou'),
    ]

    operations = [
        migrations.CreateModel(
            name='MOUAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('first_party', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('second_party', models.CharField(max_length=255)),
                ('preamble', models.TextField()),
                ('purpose', models.TextField()),
                ('pdf_doc', models.FileField(upload_to='mou_pdfs/')),
            ],
        ),
    ]
