# Generated by Django 3.1 on 2024-09-15 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_mouagreement'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mouagreement',
            table='account_mouagreement',
        ),
    ]
